client.secret=1gr3vds9grbvubgh5g3aii3tqgp3m26c6dij3nsv1tsbar2jcseu
client.id=2so1g0g0fsqq9btveterrg7n8e
oauthURL=https://eventvisualizer.auth.us-east-2.amazoncognito.com/oauth2/token
loginURL=https://eventvisualizer.auth.us-east-2.amazoncognito.com/login
redirectURL=https://eventvisualizer.us-east-2.elasticbeanstalk.com/auth
region=us-east-2
poolId=us-east-2_6Tfoen9xX